language: php
php:
  - "5.2"
  - "5.3"
  - "5.4"
  - "5.5"

env: TMPDIR=/tmp

before_install:
 - phpenv rehash
 - sh ./tests/install_dependencies.sh
 - phpenv rehash

before_script:
 - phpenv config-add travis.php.ini

script:
 - cd tests/
 - php runalltests.php
